### ISSUE TITLE
Permissions....

### ISSUE THREAD

**Issue by DueKay** [WetABQ/Nukkit-QuickShop#2]
Hallo zusammen,

ich hoffe es ist nicht schlimm, das ich in deutsch schreibe. Aber mein Englisch ist wirklich schlecht. Dennoch werde ich unter dem original Text ne Kopie aus Googe Übersetzer einfügen und hoffe, dass mir geholfen werden kann.

Ich mag das Plugin und ich wollte es gerne für meinen Adminshop benutzen. Aber leider finde ich keine Möglichkeit, normalen Usern Berechtigungen weg zu nehmen. Man müsste wenigstens das /qs unlimited für Spieler verbieten können, da diese sich sonst Geld cheaten könnten. Zudem wäre es schön wenn man die Berechtigungen das Plugins selbst auf false oder true stellen könnte, mit LuckPerms (da ich das derzeit benutze)

Ich würde mich über eine Antwort freuen

Lg DueKay

Hello everybody,

I hope it is not bad that I write in German. But my English is really bad. Nevertheless, I will insert a copy of Googe Translator under the original text and hope that I can be helped.

I like the plugin and I wanted to use it for my adminshop. But unfortunately, I find no way to take normal users away permissions. You would have to be able to ban at least the / qs unlimited for players, as they could otherwise cheat money. In addition, it would be nice if you could set the permissions on the plugin itself to false or true, with LuckPerms (since I'm currently using that)

I would appreciate an answer

Greetings DueKay

**Comment by WetABQ** [comment]
Sorry, I don't have a permission node to add a command.
The problem with the unlimited store has been fixed, please download the latest version.
