### ISSUE TITLE
Found a great bug!!!!! 

### ISSUE THREAD

**Issue by Darkfighter710** [WetABQ/Nukkit-QuickShop#4]
If you sell your own items on your own chest you will get the money but you don't have to pay. So you can set the sell price to 300.000 and if you sell thinks like dirt for that amount you get 300.000 more so you have 600000 this you can do forever for un limit money. Pls fix it. Make it impossible to buy/sell from your own shop

**Comment by WetABQ** [comment]
I can't redo that.
