### ISSUE TITLE
everybody can open chests

### ISSUE THREAD

**Issue by mercadanteus** [WetABQ/Nukkit-QuickShop#5]
Unless you use some region protection plugin with flags, all players can open chests and take the items, would be a good idea to have more permissions

**Comment by WetABQ** [comment]
Will fix it in 3 days

**Comment by mercadanteus** [comment]
Thanks, please also make the player must sneak when he touches the chest with the item to sell.  There is a problem because players must always touch any chest with signs using empty hands, otherwise the message asking to enter the price of the to sell item appears.  Great plugin

**Comment by WetABQ** [comment]
I recommend you to use this https://github.com/innc11/QuickShopX

**Comment by mercadanteus** [comment]
Thanks, but I don´t know to code, What do I use to build the jar file?

**Comment by WetABQ** [comment]
[QuickShopX-1.4.1.jar.zip](https://github.com/WetABQ/Nukkit-QuickShop/files/4188341/QuickShopX-1.4.1.jar.zip)

**Comment by mercadanteus** [comment]
Thank you very much
